FROM node:16 as base

WORKDIR /usr/src/app/frontend

ENV CI=true

COPY frontend/package*.json ./
RUN npm install
COPY ./frontend .
RUN npm run lint
RUN npm run test
RUN npm run build

WORKDIR /usr/src/app/backend
